export type Service = {
  slug: string;
  title: string;
  line: string;
  heroImage: string;
  heroImageAlt: string;
  intro: string;
  whatsIncluded: string[];
  process: { step: string; title: string; description: string }[];
  faqs: { q: string; a: string }[];
  metaTitle: string;
  metaDescription: string;
  relatedProductSlug: string;
  relatedSolutionSlugs: string[];
};

function installProcess(serviceTitle: string): Service["process"] {
  return [
    {
      step: "01",
      title: "Site Survey & Quote",
      description: `An ABHEE engineer visits the site to assess requirements for ${serviceTitle.toLowerCase()} and provide a fixed quote.`,
    },
    {
      step: "02",
      title: "Scheduling",
      description: "Installation is scheduled around your timeline, with equipment sourced and confirmed in advance.",
    },
    {
      step: "03",
      title: "Installation Day",
      description: "Certified technicians complete the installation and configuration in a single coordinated visit.",
    },
    {
      step: "04",
      title: "Handover & AMC",
      description: "The system is tested, demonstrated, and covered under ABHEE's standard warranty and optional AMC plan.",
    },
  ];
}

export const SERVICES: Service[] = [
  {
    slug: "smart-home-automation",
    title: "Smart Home Automation Installation",
    line: "Design and installation of a single automation system covering every room.",
    heroImage: "/images/services/smart-home-automation/hero.jpg",
    heroImageAlt: "Technician installing a smart home automation control panel",
    intro: "End-to-end installation of ABHEE's smart home automation system, from wiring survey to app handover.",
    whatsIncluded: [
      "Requirement assessment & wiring survey",
      "Automation hub & sensor installation",
      "App configuration & scene setup",
      "Voice assistant integration",
      "Staff/family training on the app",
    ],
    process: installProcess("Smart Home Automation"),
    faqs: [
      { q: "How long does a full smart home automation installation take?", a: "A typical villa installation takes 3-7 days depending on the number of rooms and systems involved." },
      { q: "Do you install automation in already-built homes?", a: "Yes, retrofit installation is a large part of ABHEE's automation work and avoids breaking walls in most cases." },
    ],
    metaTitle: "Smart Home Automation Installation Service | ABHEE Smart Liv",
    metaDescription: "Professional smart home automation installation — design, wiring, configuration and handover — by ABHEE Smart Liv.",
    relatedProductSlug: "smart-home-automation",
    relatedSolutionSlugs: ["villas", "apartments", "gated-communities", "offices"],
  },
  {
    slug: "home-theatre-installation",
    title: "Home Theatre Installation",
    line: "Acoustic design, equipment mounting and calibration for a dedicated cinema room.",
    heroImage: "/images/services/home-theatre-installation/hero.jpg",
    heroImageAlt: "Technician calibrating a home theatre projector and speakers",
    intro: "Full-service home theatre installation — acoustic treatment, seating layout, and audio/video calibration.",
    whatsIncluded: [
      "Room acoustic assessment & treatment",
      "Screen, projector & speaker mounting",
      "Amplifier & source equipment wiring",
      "Dolby Atmos/DTS:X calibration",
      "Automation & lighting scene integration",
    ],
    process: installProcess("Home Theatre Installation"),
    faqs: [
      { q: "Do you handle the acoustic treatment, or only the equipment?", a: "ABHEE handles both — acoustic wall/ceiling treatment is installed alongside the audio and video equipment as one project." },
      { q: "Can the theatre be integrated with existing home automation?", a: "Yes, home theatre control is integrated into the same automation app used for lighting and curtains." },
    ],
    metaTitle: "Home Theatre Installation Service | ABHEE Smart Liv",
    metaDescription: "Acoustic treatment, equipment installation and calibration for private home theatres, by ABHEE Smart Liv.",
    relatedProductSlug: "home-theatre",
    relatedSolutionSlugs: ["villas", "apartments", "hotels"],
  },
  {
    slug: "professional-audio-installation",
    title: "Professional Audio Installation",
    line: "Multi-room and P.A. sound system installation, zoned and calibrated per room.",
    heroImage: "/images/services/professional-audio-installation/hero.jpg",
    heroImageAlt: "Technician installing in-ceiling speakers",
    intro: "Installation of in-ceiling, in-wall, outdoor and P.A. sound systems, calibrated to each room or venue.",
    whatsIncluded: [
      "Speaker placement & wiring plan",
      "In-ceiling/in-wall/outdoor speaker mounting",
      "Amplifier & mixer setup",
      "Zone configuration & app control",
      "Acoustic calibration per room/venue",
    ],
    process: installProcess("Professional Audio Installation"),
    faqs: [
      { q: "Can you install a P.A. system for a function hall or school event?", a: "Yes, ABHEE installs P.A. sound systems including mixers, amplifiers and podium microphones for halls, schools and events." },
      { q: "Are outdoor speakers installed differently from indoor ones?", a: "Yes, outdoor installations use IP-rated weatherproof speakers and enclosures suited to monsoon and direct sun exposure." },
    ],
    metaTitle: "Professional Audio & P.A. System Installation | ABHEE Smart Liv",
    metaDescription: "Multi-room and P.A. sound system installation for homes, schools and function halls, by ABHEE Smart Liv.",
    relatedProductSlug: "professional-audio",
    relatedSolutionSlugs: ["villas", "function-halls", "schools", "colleges"],
  },
  {
    slug: "cctv-installation",
    title: "CCTV Installation",
    line: "AI and standard CCTV camera installation with NVR/DVR setup and remote monitoring.",
    heroImage: "/images/services/cctv-installation/hero.jpg",
    heroImageAlt: "Technician mounting a CCTV camera on an exterior wall",
    intro: "Camera placement, cabling, NVR/DVR setup and remote monitoring configuration for homes, campuses and offices.",
    whatsIncluded: [
      "Camera placement & coverage survey",
      "Camera mounting & cabling",
      "NVR/DVR installation & storage setup",
      "AI feature configuration (face/vehicle detection)",
      "Remote monitoring app setup",
    ],
    process: installProcess("CCTV Installation"),
    faqs: [
      { q: "How many cameras does a typical villa need?", a: "Most villas are well covered with 4-8 cameras across entrances, the perimeter and common areas, depending on plot size." },
      { q: "Can I view live camera feeds from my phone?", a: "Yes, every ABHEE CCTV installation includes a remote monitoring app for live and recorded footage." },
    ],
    metaTitle: "CCTV & Surveillance Camera Installation Service | ABHEE Smart Liv",
    metaDescription: "AI CCTV and surveillance camera installation with NVR/DVR setup and remote monitoring, by ABHEE Smart Liv.",
    relatedProductSlug: "ai-cctv-cameras",
    relatedSolutionSlugs: ["villas", "gated-communities", "schools", "offices", "commercial-buildings"],
  },
  {
    slug: "smart-lighting-installation",
    title: "Smart Lighting Installation",
    line: "Scene-based smart lighting installed behind your existing switches.",
    heroImage: "/images/services/smart-lighting-installation/hero.jpg",
    heroImageAlt: "Technician installing a smart lighting switch module",
    intro: "Installation of smart lighting modules, scene programming and schedule setup, mostly without new wiring.",
    whatsIncluded: [
      "Switchboard & circuit assessment",
      "Smart module installation behind existing switches",
      "Scene & schedule programming",
      "Voice assistant pairing",
      "App handover & training",
    ],
    process: installProcess("Smart Lighting Installation"),
    faqs: [
      { q: "Will installing smart lighting require breaking my walls?", a: "In most retrofits, smart modules fit behind existing switch plates, so no wall-breaking or rewiring is needed." },
      { q: "Can lighting scenes be scheduled to change automatically?", a: "Yes, scenes can be scheduled by time of day or triggered by sunset/sunrise." },
    ],
    metaTitle: "Smart Lighting Installation Service | ABHEE Smart Liv",
    metaDescription: "Scene-based smart lighting installation, mostly retrofit-friendly, by ABHEE Smart Liv.",
    relatedProductSlug: "smart-lighting",
    relatedSolutionSlugs: ["villas", "apartments", "gated-communities", "function-halls"],
  },
  {
    slug: "smart-door-lock-installation",
    title: "Smart Door Lock Installation",
    line: "Fingerprint, PIN, card and app-based lock installation on any standard door.",
    heroImage: "/images/services/smart-door-lock-installation/hero.jpg",
    heroImageAlt: "Technician installing a smart fingerprint door lock",
    intro: "Fitting and configuration of smart door locks, including fingerprint enrolment and app setup.",
    whatsIncluded: [
      "Door & frame compatibility check",
      "Lock body & keypad/fingerprint module fitting",
      "Battery backup installation",
      "User/fingerprint/PIN enrolment",
      "App pairing & alert setup",
    ],
    process: installProcess("Smart Door Lock Installation"),
    faqs: [
      { q: "Will a smart lock fit my existing door?", a: "Most standard wooden and metal doors are compatible; ABHEE checks door thickness and frame type before installation." },
      { q: "What if the lock's battery dies?", a: "Every installation includes a physical key override and advance low-battery alerts to your phone." },
    ],
    metaTitle: "Smart Door Lock Installation Service | ABHEE Smart Liv",
    metaDescription: "Fingerprint, PIN, card and app-based smart door lock installation, by ABHEE Smart Liv.",
    relatedProductSlug: "smart-door-locks",
    relatedSolutionSlugs: ["villas", "apartments", "hotels", "offices"],
  },
  {
    slug: "video-door-phone-installation",
    title: "Video Door Phone Installation",
    line: "HD video door phone and intercom installation, wired or wireless.",
    heroImage: "/images/services/video-door-phone-installation/hero.jpg",
    heroImageAlt: "Technician installing a video door phone at an entrance",
    intro: "Installation of video door phones and wired/wireless intercom networks across doors, gates and cabins.",
    whatsIncluded: [
      "Entry point & wiring assessment",
      "Outdoor unit & indoor monitor mounting",
      "Wired/wireless intercom network setup",
      "Mobile app pairing",
      "Multi-point testing (gate, door, cabin)",
    ],
    process: installProcess("Video Door Phone Installation"),
    faqs: [
      { q: "Can the video door phone connect to my phone when I'm away?", a: "Yes, the app provides live video and two-way talk from anywhere with an internet connection." },
      { q: "Can you connect the gate, main door and security cabin on one intercom network?", a: "Yes, ABHEE designs wired or wireless intercom networks that link every access point in a home or community." },
    ],
    metaTitle: "Video Door Phone & Intercom Installation Service | ABHEE Smart Liv",
    metaDescription: "Video door phone and wired/wireless intercom installation for homes and gated communities, by ABHEE Smart Liv.",
    relatedProductSlug: "video-door-phones",
    relatedSolutionSlugs: ["villas", "apartments", "gated-communities"],
  },
  {
    slug: "access-control-installation",
    title: "Access Control Installation",
    line: "Biometric and card-based access control across doors, floors and campuses.",
    heroImage: "/images/services/access-control-installation/hero.jpg",
    heroImageAlt: "Technician installing a biometric access control reader",
    intro: "Installation of biometric/card access control, security sensors and vehicle tracking across buildings and campuses.",
    whatsIncluded: [
      "Access point & user-flow mapping",
      "Reader & controller installation",
      "Security sensor placement",
      "GPS vehicle tracker fitting (where applicable)",
      "User enrolment & permission setup",
    ],
    process: installProcess("Access Control Installation"),
    faqs: [
      { q: "Can access control be set up with different permissions per user?", a: "Yes, ABHEE configures zone-based permissions so different users or departments have different access rights." },
      { q: "Do you install GPS tracking for school buses as part of this service?", a: "Yes, GPS vehicle tracker installation and dashboard setup is offered alongside access control for schools." },
    ],
    metaTitle: "Access Control System Installation Service | ABHEE Smart Liv",
    metaDescription: "Biometric and card-based access control installation for offices, schools and commercial buildings, by ABHEE Smart Liv.",
    relatedProductSlug: "access-control-systems",
    relatedSolutionSlugs: ["offices", "commercial-buildings", "schools", "colleges", "hospitals"],
  },
  {
    slug: "gate-automation-installation",
    title: "Gate Automation Installation",
    line: "Motorised sliding and swing gate installation with app and remote control.",
    heroImage: "/images/services/gate-automation-installation/hero.jpg",
    heroImageAlt: "Technician installing a sliding gate motor",
    intro: "Installation of motorised sliding and swing gate operators, integrated with remotes, app and video door phones.",
    whatsIncluded: [
      "Gate weight & track assessment",
      "Motor & operator installation",
      "Remote, RFID & app pairing",
      "Battery backup setup",
      "Integration with video door phone/CCTV",
    ],
    process: installProcess("Gate Automation Installation"),
    faqs: [
      { q: "Can an existing manual gate be automated?", a: "Yes, most existing sliding and swing gates can be fitted with a motor and operator without replacing the gate itself." },
      { q: "Does the gate work during a power cut?", a: "Yes, battery backup keeps the gate operational for several hours during outages." },
    ],
    metaTitle: "Gate Automation Installation Service | ABHEE Smart Liv",
    metaDescription: "Motorised sliding and swing gate installation with app, remote and RFID control, by ABHEE Smart Liv.",
    relatedProductSlug: "remote-gates",
    relatedSolutionSlugs: ["villas", "gated-communities", "offices"],
  },
  {
    slug: "boom-barrier-installation",
    title: "Boom Barrier Installation",
    line: "Automatic boom barrier installation for community and commercial vehicle entrances.",
    heroImage: "/images/services/boom-barrier-installation/hero.jpg",
    heroImageAlt: "Automatic boom barrier at a gated community vehicle entrance",
    intro: "Installation of automatic boom barriers with RFID/number-plate recognition for high vehicle-traffic entrances.",
    whatsIncluded: [
      "Traffic flow & entrance survey",
      "Boom barrier arm & motor installation",
      "RFID/ANPR reader setup",
      "Integration with CCTV & access logs",
      "Load testing & handover",
    ],
    process: installProcess("Boom Barrier Installation"),
    faqs: [
      { q: "Can resident vehicles pass through without stopping?", a: "Yes, with RFID tags or number-plate recognition configured, resident vehicles are recognised automatically." },
      { q: "Is a boom barrier suitable for a function hall's event traffic?", a: "Yes, boom barriers are commonly installed at function halls to manage high vehicle volume during events." },
    ],
    metaTitle: "Boom Barrier Installation Service | ABHEE Smart Liv",
    metaDescription: "Automatic boom barrier installation with RFID and ANPR for gated communities and commercial entrances, by ABHEE Smart Liv.",
    relatedProductSlug: "remote-gates",
    relatedSolutionSlugs: ["gated-communities", "function-halls", "commercial-buildings"],
  },
  {
    slug: "motorized-curtain-installation",
    title: "Motorized Curtain Installation",
    line: "Motorised curtain track installation on existing or new curtain fabric.",
    heroImage: "/images/services/motorized-curtain-installation/hero.jpg",
    heroImageAlt: "Technician installing a motorized curtain track",
    intro: "Fitting of whisper-quiet motorised curtain tracks, configured for app, voice and schedule control.",
    whatsIncluded: [
      "Window & fabric compatibility check",
      "Motorised track installation",
      "Motor wiring/battery setup",
      "App & voice assistant pairing",
      "Schedule configuration (sunrise/sunset)",
    ],
    process: installProcess("Motorized Curtain Installation"),
    faqs: [
      { q: "Will my existing curtains work with a motorised track?", a: "In most cases yes — ABHEE's tracks are designed to accommodate existing curtain fabric without a full replacement." },
      { q: "Can curtains open automatically at sunrise?", a: "Yes, schedules can be tied to a fixed time or to sunrise/sunset triggers." },
    ],
    metaTitle: "Motorized Curtain Installation Service | ABHEE Smart Liv",
    metaDescription: "Motorised curtain track installation with app, voice and schedule control, by ABHEE Smart Liv.",
    relatedProductSlug: "motorized-curtains",
    relatedSolutionSlugs: ["villas", "apartments", "offices"],
  },
  {
    slug: "motorized-blind-installation",
    title: "Motorized Blind Installation",
    line: "Motorised blinds and transparent elevation shutters for glare, privacy and facades.",
    heroImage: "/images/services/motorized-blind-installation/hero.jpg",
    heroImageAlt: "Motorized blinds installed on a large window",
    intro: "Installation of motorised blinds and transparent elevation motorized shutters for balconies and facades.",
    whatsIncluded: [
      "Window/facade measurement & survey",
      "Blind or shutter mechanism installation",
      "Motor wiring & control setup",
      "App & schedule configuration",
      "Load & weather testing",
    ],
    process: installProcess("Motorized Blind Installation"),
    faqs: [
      { q: "What are transparent elevation motorized shutters?", a: "They're motorised glass or slatted shutter systems fitted to balconies and facades, letting you open or seal an elevation at the touch of a button." },
      { q: "Can blinds and curtains be controlled from the same app?", a: "Yes, blinds, shutters and curtains are all managed from the same ABHEE automation app." },
    ],
    metaTitle: "Motorized Blind & Elevation Shutter Installation | ABHEE Smart Liv",
    metaDescription: "Motorised blinds and transparent elevation shutter installation for villas and offices, by ABHEE Smart Liv.",
    relatedProductSlug: "motorized-curtains",
    relatedSolutionSlugs: ["villas", "offices"],
  },
  {
    slug: "solar-fencing-installation",
    title: "Solar Fencing Installation",
    line: "Solar-powered perimeter fencing installation with instant breach alerts.",
    heroImage: "/images/services/solar-fencing-installation/hero.jpg",
    heroImageAlt: "Technician installing solar fencing along a boundary wall",
    intro: "Installation of solar-powered perimeter fencing along boundary walls, with breach-alert configuration.",
    whatsIncluded: [
      "Perimeter survey & wire routing plan",
      "Solar energizer & wire installation",
      "Breach-alert sensor configuration",
      "Integration with gate & CCTV systems",
      "Safety compliance testing",
    ],
    process: installProcess("Solar Fencing Installation"),
    faqs: [
      { q: "Does solar fencing need a mains power connection?", a: "No, the system runs entirely on solar power, with no impact on your electricity bill." },
      { q: "Is the fence safe for children and pets nearby?", a: "Yes, ABHEE configures fencing to pulse a safe, non-lethal deterrent shock matching Indian safety standards." },
    ],
    metaTitle: "Solar Fencing Installation Service | ABHEE Smart Liv",
    metaDescription: "Solar-powered perimeter fencing installation with breach alerts, for villas and gated communities, by ABHEE Smart Liv.",
    relatedProductSlug: "solar-fencing",
    relatedSolutionSlugs: ["villas", "gated-communities", "function-halls", "schools"],
  },
  {
    slug: "led-wall-installation",
    title: "LED Wall Installation",
    line: "Indoor LED display wall installation for stages, lobbies and events.",
    heroImage: "/images/services/led-wall-installation/hero.jpg",
    heroImageAlt: "LED display wall installed on a function hall stage",
    intro: "Structural mounting, panel assembly and calibration of indoor LED display walls for stages and lobbies.",
    whatsIncluded: [
      "Viewing distance & pixel-pitch planning",
      "Structural frame & panel mounting",
      "Video processor & source wiring",
      "Colour & brightness calibration",
      "Content playback setup",
    ],
    process: installProcess("LED Wall Installation"),
    faqs: [
      { q: "What size LED wall does a function hall stage need?", a: "ABHEE recommends a pixel pitch and size based on the stage dimensions and typical viewing distance in the hall." },
      { q: "Can the LED wall play live camera feeds during an event?", a: "Yes, video processors can switch between pre-loaded content and live camera or laptop input." },
    ],
    metaTitle: "LED Wall Installation Service | ABHEE Smart Liv",
    metaDescription: "Indoor LED display wall installation for function hall stages, schools and corporate lobbies, by ABHEE Smart Liv.",
    relatedProductSlug: "projectors",
    relatedSolutionSlugs: ["function-halls", "schools", "colleges", "offices"],
  },
  {
    slug: "projector-installation",
    title: "Projector Installation",
    line: "4K and laser projector installation with motorised screens and calibration.",
    heroImage: "/images/services/projector-installation/hero.jpg",
    heroImageAlt: "Technician mounting a ceiling projector",
    intro: "Ceiling or shelf mounting, screen installation and colour/focus calibration for 4K and laser projectors.",
    whatsIncluded: [
      "Throw-distance & mounting survey",
      "Projector & bracket installation",
      "Motorised screen installation",
      "Source device wiring",
      "Colour, focus & keystone calibration",
    ],
    process: installProcess("Projector Installation"),
    faqs: [
      { q: "Can a projector work well in a room with daylight?", a: "Yes, with an ambient-light rejecting screen and a higher-lumen laser projector, recommended for rooms with daylight." },
      { q: "Do you install projectors for school auditoriums?", a: "Yes, ABHEE installs and calibrates projectors and screens for school and college auditoriums alongside podium AV." },
    ],
    metaTitle: "Projector Installation Service | ABHEE Smart Liv",
    metaDescription: "4K and laser projector installation with motorised screens, for home theatres, schools and offices, by ABHEE Smart Liv.",
    relatedProductSlug: "projectors",
    relatedSolutionSlugs: ["villas", "schools", "colleges", "function-halls", "offices"],
  },
  {
    slug: "wooden-flooring-installation",
    title: "Wooden Flooring Installation",
    line: "Engineered and laminate wooden flooring installation rated for Indian climates.",
    heroImage: "/images/services/wooden-flooring-installation/hero.jpg",
    heroImageAlt: "Installer laying engineered wooden flooring planks",
    intro: "Subfloor preparation and installation of engineered or laminate wooden flooring across rooms or gym floors.",
    whatsIncluded: [
      "Subfloor levelling & moisture check",
      "Underlay installation",
      "Plank fitting & finishing",
      "Skirting & transition trims",
      "Final clean & inspection",
    ],
    process: installProcess("Wooden Flooring Installation"),
    faqs: [
      { q: "How long does flooring installation take for an average room?", a: "A typical living room or bedroom is completed in 1-2 days, depending on subfloor condition." },
      { q: "Do you install gym-grade wooden flooring too?", a: "Yes, ABHEE installs studio and gym-grade wooden flooring in addition to residential finishes." },
    ],
    metaTitle: "Wooden Flooring Installation Service | ABHEE Smart Liv",
    metaDescription: "Engineered and laminate wooden flooring installation for homes, offices and gyms, by ABHEE Smart Liv.",
    relatedProductSlug: "wooden-flooring",
    relatedSolutionSlugs: ["villas", "apartments", "gated-communities", "offices"],
  },
  {
    slug: "artificial-lawn-installation",
    title: "Artificial Lawn Installation",
    line: "UV-stable artificial grass installation for gardens, terraces and balconies.",
    heroImage: "/images/services/artificial-lawn-installation/hero.jpg",
    heroImageAlt: "Installer laying artificial grass in a garden",
    intro: "Base preparation and installation of UV-stable artificial lawn across gardens, terraces and balconies.",
    whatsIncluded: [
      "Ground/terrace levelling & drainage check",
      "Base layer preparation",
      "Artificial grass laying & seaming",
      "Edge fixing & infill",
      "Final grooming & inspection",
    ],
    process: installProcess("Artificial Lawn Installation"),
    faqs: [
      { q: "Can artificial lawn be installed on a terrace or balcony?", a: "Yes, ABHEE installs artificial lawn on terraces and balconies with a suitable drainage-ready base." },
      { q: "Does artificial grass need any watering or mowing?", a: "No, it requires zero watering or mowing and stays green through every season." },
    ],
    metaTitle: "Artificial Lawn Installation Service | ABHEE Smart Liv",
    metaDescription: "UV-stable artificial grass installation for gardens, terraces and balconies, by ABHEE Smart Liv.",
    relatedProductSlug: "artificial-grass",
    relatedSolutionSlugs: ["villas", "apartments", "gated-communities"],
  },
  {
    slug: "sports-flooring-installation",
    title: "Sports Flooring Installation",
    line: "Courts, turf and synthetic sports flooring installation for campuses and communities.",
    heroImage: "/images/services/sports-flooring-installation/hero.jpg",
    heroImageAlt: "Installer laying synthetic sports court flooring",
    intro: "Installation of wooden shuttle courts, basketball/volleyball courts, running tracks, astro turf and synthetic sports flooring.",
    whatsIncluded: [
      "Court/turf layout & base survey",
      "Base preparation & levelling",
      "Court marking & surface laying",
      "PP tiles/synthetic paint application",
      "Line marking & handover",
    ],
    process: installProcess("Sports Flooring Installation"),
    faqs: [
      { q: "Can one project cover both a running track and indoor courts?", a: "Yes, ABHEE coordinates outdoor turf/track work and indoor court installation as a single project." },
      { q: "How long does synthetic sports flooring last?", a: "Quality PP tiles and synthetic paint surfaces typically last 8-10 years with normal community or school use." },
    ],
    metaTitle: "Sports Flooring & Court Installation Service | ABHEE Smart Liv",
    metaDescription: "Sports court, turf and synthetic flooring installation for schools, colleges and gated communities, by ABHEE Smart Liv.",
    relatedProductSlug: "sports-recreational-solutions",
    relatedSolutionSlugs: ["gated-communities", "schools", "colleges", "villas"],
  },
  {
    slug: "swimming-pool-automation",
    title: "Swimming Pool Automation",
    line: "Pool filtration, pump and lighting automation integrated with your home system.",
    heroImage: "/images/services/swimming-pool-automation/hero.jpg",
    heroImageAlt: "Automated pool filtration and lighting equipment installation",
    intro: "Installation of automated filtration, pump control and lighting systems for new or existing swimming pools.",
    whatsIncluded: [
      "Pool system & equipment assessment",
      "Filtration & pump automation wiring",
      "Underwater/deck lighting installation",
      "App integration with home automation",
      "Water quality monitoring setup",
    ],
    process: installProcess("Swimming Pool Automation"),
    faqs: [
      { q: "Can pool automation be added to an existing pool?", a: "Yes, ABHEE retrofits filtration and lighting automation onto existing pools, not only new construction." },
      { q: "Is pool lighting controlled from the same app as the rest of the house?", a: "Yes, pool pumps, filtration and lighting integrate into the same automation app used indoors." },
    ],
    metaTitle: "Swimming Pool Automation Installation Service | ABHEE Smart Liv",
    metaDescription: "Swimming pool filtration, pump and lighting automation installation for villas and gated communities, by ABHEE Smart Liv.",
    relatedProductSlug: "swimming-pool-lifestyle-automation",
    relatedSolutionSlugs: ["villas", "gated-communities", "hotels"],
  },
  {
    slug: "gym-equipment-installation",
    title: "Gym Equipment Installation",
    line: "Selection, delivery and fit-out of home and community gym equipment.",
    heroImage: "/images/services/gym-equipment-installation/hero.jpg",
    heroImageAlt: "Installer assembling gym equipment in a home fitness room",
    intro: "Equipment selection, delivery, assembly and layout for home, villa and community gyms.",
    whatsIncluded: [
      "Space & flooring assessment",
      "Equipment selection & sourcing",
      "Delivery & assembly",
      "Layout & safety spacing",
      "Maintenance briefing",
    ],
    process: installProcess("Gym Equipment Installation"),
    faqs: [
      { q: "Do you also install the gym flooring, or only the equipment?", a: "ABHEE can coordinate both gym-grade flooring and equipment fit-out as one project." },
      { q: "Can you set up a gym for a gated community clubhouse?", a: "Yes, ABHEE sizes and fits out gym equipment for community clubhouses as well as private home gyms." },
    ],
    metaTitle: "Gym Equipment Installation Service | ABHEE Smart Liv",
    metaDescription: "Gym equipment selection, delivery and fit-out for villas and gated community clubhouses, by ABHEE Smart Liv.",
    relatedProductSlug: "swimming-pool-lifestyle-automation",
    relatedSolutionSlugs: ["villas", "gated-communities"],
  },
];

export function getServiceBySlug(slug: string) {
  return SERVICES.find((s) => s.slug === slug);
}
